version: '3.8'

services:
  front:
    container_name: spacedate_front
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
    - 3000:3000
    volumes:
      - /usr/src/app/node_modules